import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

async function main() {
  console.log("Seeding database with sample HS Code data (Chapter 01)...");

  // Clear existing data
  await prisma.hsCode.deleteMany();

  const sampleData = [
    // Section/Chapter headers
    {
      maHang: "CHƯƠNG 01",
      moTaViet: "ĐỘNG VẬT SỐNG",
      isHeader: true,
    },
    {
      maHang: "0101",
      moTaViet: "Ngựa, lừa, la sống:",
      isHeader: true,
    },
    {
      maHang: "01011000",
      moTaViet: "Loại thuần chủng để nhân giống",
      donViTinh: "kg/con",
      nkTt: "0",
      nkUuDai: "0",
      vat: "5",
      acfta: "0",
      atiga: "0",
      evfta: "0",
      cptpp: "0",
      xk: "0",
    },
    {
      maHang: "01019000",
      moTaViet: "Loại khác",
      donViTinh: "kg/con",
      nkTt: "5",
      nkUuDai: "0",
      vat: "5",
      acfta: "0",
      atiga: "0",
      evfta: "0",
      cptpp: "0",
      xk: "0",
    },
    {
      maHang: "0102",
      moTaViet: "Trâu, bò sống:",
      isHeader: true,
    },
    {
      maHang: "- Gia súc:",
      moTaViet: "- Gia súc:",
      isHeader: true,
    },
    {
      maHang: "01022100",
      moTaViet: "Loại thuần chủng để nhân giống",
      donViTinh: "kg/con",
      nkTt: "5",
      nkUuDai: "0",
      vat: "*/8/10",
      acfta: "0",
      atiga: "0",
      aicep: "0",
      vjepa: "0",
      akfta: "0",
      aanzfta: "0",
      aifta: "0",
      vkfta: "0",
      vcfta: "0",
      vneaeu: "0",
      cptpp: "0",
      ahkfta: "0",
      evfta: "0",
      ukvfta: "0",
      xk: "0",
      chinhSachMatHang:
        "Động vật, sản phẩm động vật trên cạn phải kiểm dịch (01 - Động vật sống)",
    },
    {
      maHang: "01022911",
      moTaViet: "Bò thiến (GEN)",
      donViTinh: "kg/con",
      nkTt: "7.5",
      nkUuDai: "5",
      vat: "*/5/8/10",
      acfta: "3",
      atiga: "0",
      aicep: "5",
      vjepa: "5",
      akfta: "5",
      aanzfta: "5",
      aifta: "5",
      vkfta: "5",
      vcfta: "5",
      vneaeu: "5",
      cptpp: "3",
      ahkfta: "5",
      evfta: "5",
      ukvfta: "5",
      xk: "0",
      chinhSachMatHang:
        "Động vật, sản phẩm động vật trên cạn phải kiểm dịch (01 - Động vật sống)",
    },
    {
      maHang: "01022919",
      moTaViet: "Loại khác",
      donViTinh: "kg/con",
      nkTt: "7.5",
      nkUuDai: "5",
      vat: "*/5/8/10",
      acfta: "3",
      atiga: "0",
      cptpp: "3",
      evfta: "5",
      xk: "0",
      chinhSachMatHang:
        "Động vật, sản phẩm động vật trên cạn phải kiểm dịch (01 - Động vật sống)",
    },
    {
      maHang: "01022990",
      moTaViet: "Loại khác",
      donViTinh: "kg/con",
      nkTt: "7.5",
      nkUuDai: "5",
      vat: "*/5/8/10",
      acfta: "5",
      atiga: "0",
      cptpp: "3",
      evfta: "5",
      xk: "0",
    },
    {
      maHang: "- - Trâu:",
      moTaViet: "- - Trâu:",
      isHeader: true,
    },
    {
      maHang: "01023100",
      moTaViet: "Loại thuần chủng để nhân giống",
      donViTinh: "kg/con",
      nkTt: "5",
      nkUuDai: "0",
      vat: "*/8/10",
      acfta: "0",
      atiga: "0",
      cptpp: "0",
      evfta: "0",
      xk: "0",
      chinhSachMatHang:
        "Động vật, sản phẩm động vật trên cạn phải kiểm dịch (01 - Động vật sống)",
    },
    {
      maHang: "01023900",
      moTaViet: "Loại khác",
      donViTinh: "kg/con",
      nkTt: "7.5",
      nkUuDai: "5",
      vat: "*/5/8/10",
      acfta: "5",
      atiga: "5",
      cptpp: "5",
      evfta: "5",
      xk: "0",
    },
    {
      maHang: "01029010",
      moTaViet: "Loại thuần chủng để nhân giống",
      donViTinh: "kg/con",
      nkTt: "5",
      nkUuDai: "0",
      vat: "*/8/10",
      acfta: "0",
      atiga: "0",
      cptpp: "0",
      evfta: "0",
      xk: "0",
    },
    {
      maHang: "01029090",
      moTaViet: "Loại khác",
      donViTinh: "kg/con",
      nkTt: "7.5",
      nkUuDai: "5",
      vat: "*/5/8/10",
      acfta: "5",
      atiga: "5",
      cptpp: "5",
      evfta: "5",
      xk: "0",
    },
    {
      maHang: "Lợn sống",
      moTaViet: "Lợn sống",
      isHeader: true,
    },
    {
      maHang: "01031000",
      moTaViet: "Loại thuần chủng để nhân giống",
      donViTinh: "kg/con",
      nkTt: "5",
      nkUuDai: "0",
      vat: "8",
      acfta: "0",
      atiga: "0",
      cptpp: "0",
      evfta: "0",
      xk: "0",
      chinhSachMatHang:
        "Động vật, sản phẩm động vật trên cạn phải kiểm dịch (01 - Động vật sống)",
    },
    {
      maHang: "01039100",
      moTaViet: "Trọng lượng dưới 50 kg",
      donViTinh: "kg/con",
      nkTt: "10",
      nkUuDai: "5",
      vat: "*/5/8/10",
      acfta: "5",
      atiga: "5",
      cptpp: "5",
      evfta: "5",
      xk: "0",
    },
    {
      maHang: "01039200",
      moTaViet: "Trọng lượng từ 50 kg trở lên",
      donViTinh: "kg/con",
      nkTt: "10",
      nkUuDai: "5",
      vat: "*/5/8/10",
      acfta: "5",
      atiga: "5",
      cptpp: "5",
      evfta: "5",
      xk: "0",
    },
    {
      maHang: "Gia cầm sống",
      moTaViet: "Gia cầm sống, thuộc các loài thuộc họ Gallus domesticus, vịt, ngỗng, gà tây và gà sao",
      isHeader: true,
    },
    {
      maHang: "01051100",
      moTaViet: "Gà giống thuần chủng",
      donViTinh: "kg/con",
      nkTt: "5",
      nkUuDai: "0",
      vat: "5",
      acfta: "0",
      atiga: "0",
      cptpp: "0",
      evfta: "0",
      xk: "0",
      chinhSachMatHang:
        "Động vật, sản phẩm động vật trên cạn phải kiểm dịch (01 - Động vật sống)",
    },
    {
      maHang: "01051200",
      moTaViet: "Gà tây giống thuần chủng",
      donViTinh: "kg/con",
      nkTt: "5",
      nkUuDai: "0",
      vat: "5",
      acfta: "0",
      atiga: "0",
      cptpp: "0",
      evfta: "0",
      xk: "0",
    },
    {
      maHang: "01059400",
      moTaViet: "Gà thuộc loài Gallus domesticus",
      donViTinh: "kg/con",
      nkTt: "15",
      nkUuDai: "5",
      vat: "*/5/8/10",
      acfta: "5",
      atiga: "5",
      cptpp: "5",
      evfta: "5",
      xk: "0",
    },
    {
      maHang: "01059900",
      moTaViet: "Loại khác",
      donViTinh: "kg/con",
      nkTt: "15",
      nkUuDai: "5",
      vat: "*/5/8/10",
      acfta: "5",
      atiga: "5",
      cptpp: "5",
      evfta: "5",
      xk: "0",
    },
  ];

  for (const item of sampleData) {
    await prisma.hsCode.create({
      data: item,
    });
  }

  console.log(`Seeded ${sampleData.length} records successfully.`);
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
